### ISSUE TITLE
Getting error at serverless deploy

### ISSUE THREAD

**Issue by bala1074** [Snyk/serverless-snyk#20]
`npm install serverless-snyk --save`

_serverless.yml_
```
plugins:
   - serverless-snyk
```
**Getting error on `serverless deploy`**
```
 Error: Cannot find module 'snyk/lib'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
      at Function.Module._load (internal/modules/cjs/loader.js:506:25)
      at Module.require (internal/modules/cjs/loader.js:636:17)
      at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by akpsgit** [comment]
Changing to snyk instead of snyk/lib solved it for me.
